 1. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [1]:
import numpy as np

# create a vector of length 5 filled with random integers between 0 and 10
my_vector = np.random.randint(low=0, high=11, size=5)

print(my_vector)

[5 3 6 5 4]


2. Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values​​except the first and last.

In [2]:
import numpy as np

# Create a vector with values ranging from 15 to 55
vector = np.arange(15, 56)

# Print all values except the first and last
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


3. Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements

In [3]:
import numpy as np

# Create a random array with 1000 elements
arr = np.random.rand(1000)

# Compute the average, variance, and standard deviation of the array
avg = np.mean(arr)
variance = np.var(arr)
std_dev = np.std(arr)

# Print the results
print("Average: ", avg)
print("Variance: ", variance)
print("Standard Deviation: ", std_dev)

Average:  0.495613526292376
Variance:  0.0853450509995126
Standard Deviation:  0.2921387529916437


4. Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array. 

In [6]:
# Define the two matrices
matrix1 = np.array([[1, 0], [0, 1]])
matrix2 = np.array([[1, 2], [3, 4]])

# Compute the multiplication of the two matrices
result = np.dot(matrix1, matrix2)

# Print the result
print(result)

[[1 2]
 [3 4]]


5. Write a NumPy program to compute the multiplication of two given matrixes. 

Sample Matrix: 

[[1, 0], [0, 1]] 

[[1, 2], [3, 4]] 

In [7]:
# Create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the cumulative sum along axis 0
cumulative_sum_axis0 = np.cumsum(arr, axis=0)

# Calculate the cumulative sum along axis 1
cumulative_sum_axis1 = np.cumsum(arr, axis=1)

# Sum over rows for each of the 3 columns
sum_columns = np.sum(arr, axis=0)

# Sum over columns for each of the 2 rows
sum_rows = np.sum(arr, axis=1)

# Print the results
print("Cumulative sum along axis 0:\n", cumulative_sum_axis0)
print("Cumulative sum along axis 1:\n", cumulative_sum_axis1)
print("Sum over rows for each of the 3 columns:\n", sum_columns)
print("Sum over columns for each of the 2 rows:\n", sum_rows)

Cumulative sum along axis 0:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
Cumulative sum along axis 1:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Sum over rows for each of the 3 columns:
 [12 15 18]
Sum over columns for each of the 2 rows:
 [ 6 15 24]
